name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7  # Usamos una imagen de MySQL
        ports:
          - 3306:3306
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          APP_KEY: ${{ secrets.APP_KEY }}

        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-timeout=30s
          --health-start-period=10s
          --health-retries=3

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install php-cli php-mbstring php-xml php-mysql unzip curl
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Checkout repository
      run: git clone https://github.com/sala2-20/api-egym2.git

    - name: Install dependencies
      run: |
        cd api-egym2
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload
        chmod +x vendor/bin/phpunit
        
    - name: Set up environment file
      run: |
        cd api-egym2
        ./vendor/bin/phpunit --configuration phpunit.xml
        ls -la
        if [ -f test ]; then
           cp test .env
           echo "Archivo .env.example encontrado y copiado correctamente."
        else
           echo "No se encontró .env.example"
           exit 1
        fi
        php artisan key:generate
        php artisan migrate --env=testing


    - name: Run tests
      run: |
        cd api-egym2
        ./vendor/bin/phpunit --configuration phpunit.xml
